index:
    path: /
    controller: App\Controller\PageController:index

catch_all:
    path: /{url}
    defaults: { _controller: App\Controller\PageController:catchAllAction }
    methods: [ GET ]
    requirements:
        url: '.+'